steps:
 - id: setup
   name: fishtownanalytics/dbt:0.20.0
   entrypoint: 'bash'
   args:
     - '-c'
     - |
         echo "[TOOL INFORMATION]"
         dbt --version
         echo $$sakey > ./dbt-sa.json 2>/dev/null
         echo "[INSTALLING DEPENDENCIES]"
         dbt deps --profiles-dir./
         echo "[TESTING CONNECTION]"
         dbt debug --profiles-dir ./  
   secretEnv: ['sakey']
 - id: run
   name: fishtownanalytics/dbt:0.20.0
   entrypoint: 'bash'
   args:
     - '-c'
     - |
          echo "[DBT RUN]"
          dbt run --profiles-dir ./ --no-version-check
 - id: copy_files
   name: gcr.io/cloud-builders/gsutil
   entrypoint: 'bash'
   args: ['-m', 'cp', '-r', 'profiles.yml', 'gs://us-east1-dbt-test-airflow-ad1799c3-bucket/data/dbt']
availableSecrets:
 secretManager:
   - versionName: projects/julien-test-297518/secrets/dbt-sa/versions/1
     env: sakey