steps:
 - id: setup
   name: fishtownanalytics/dbt:${_DBT_VERSION}
   entrypoint: 'bash'
   args:
     - '-c'
     - |
         echo "[TOOL INFORMATION]"
         dbt --version
         echo $$sakey > ./dbt-sa.json 2>/dev/null
         echo "[INSTALLING DEPENDENCIES]"
         dbt deps --profiles-dir ./
         echo "[TESTING CONNECTION]"
         dbt debug --profiles-dir ./  
   secretEnv: ['sakey']
 - id: run
   name: fishtownanalytics/dbt:${_DBT_VERSION}
   entrypoint: 'bash'
   args:
     - '-c'
     - |
          echo "[DBT RUN]"
          dbt run --profiles-dir ./ --no-version-check
 - id: copy_files
   name: gcr.io/cloud-builders/gsutil
   entrypoint: 'bash'
   args:
     - '-c'
     - |
        echo "[COPYING DBT FILES TO GCS]"
        gsutil cp -r models ${_AIRFLOW_BUCKET}/${_DBT_PROJECT_PATH}
        gsutil cp target/manifest.json ${_AIRFLOW_BUCKET}/${_DBT_PROJECT_PATH}/airflow/
        gsutil cp profiles.yml ${_AIRFLOW_BUCKET}/${_DBT_PROJECT_PATH}/
        gsutil cp dbt_project.yml ${_AIRFLOW_BUCKET}/${_DBT_PROJECT_PATH}/
availableSecrets:
 secretManager:
   - versionName: projects/${PROJECT_ID}/secrets/${_SECRET_KEY}/versions/1
     env: sakey
