steps:
 - name: fishtownanalytics/dbt:0.19.2
   entrypoint: 'bash'
   args:
     - '-c'
     - |
         dbt --version
         echo $$sakey > ./dbt-sa.json 2>/dev/null
         dbt debug --profiles-dir ./  
   secretEnv: ['sakey']
availableSecrets:
 secretManager:
   - versionName: projects/julien-test-297518/secrets/dbt-sa/versions/1
     env: sakey